---
title: "Challenge 11"
author: "Chloe Tan"
format: html
editor: visual
---

## Graphs

```{r}
#| echo: false

library(tidyverse)
library(ggplot2)
library(httr)
 library(jsonlite)
library(cowplot)


historic_state_data_url <- "https://api.covidactnow.org/v2/states.timeseries.json?apiKey=19718ea06d7e476993d61dd560968285"

raw_data<-GET(historic_state_data_url)
data<-fromJSON(rawToChar(raw_data$content))


time_series <- data %>%unnest(actualsTimeseries)

time_series_cases <- list(Alaska = time_series %>% filter(state=="AK") %>% select(date,cases))
 time_series_cases$California <- time_series %>% filter(state=="CA") %>% select(date,cases)
 time_series_cases$New_Jersey <- time_series %>% filter(state=="NJ") %>% select(date,cases)
 time_series_cases$Tennessee <- time_series %>% filter(state=="TN") %>% select(date,cases)
 time_series_cases$District_of_Columbia <- time_series %>% filter(state=="DC") %>% select(date,cases)

data_to_plot <- tibble(Date_Alaska=time_series_cases$Alaska$date[seq(1,1300,by=100)],
Cases_Alaska = time_series_cases$Alaska$cases[seq(1,1300,by=100)],
Date_California =time_series_cases$California$date[seq(1,1300,by=100)],
Cases_California=time_series_cases$California$cases[seq(1,1300,by=100)],
Date_New_Jersey =time_series_cases$New_Jersey$date[seq(1,1300,by=100)],
Cases_New_Jersey=time_series_cases$New_Jersey$cases[seq(1,1300,by=100)],
Date_Tennessee =time_series_cases$Tennessee$date[seq(1,1300,by=100)],
Cases_Tennessee =time_series_cases$Tennessee$cases[seq(1,1300,by=100)],
Date_District_of_Columbia=time_series_cases$District_of_Columbia$date[seq(1,1300,by=100)],
Cases_District_of_Columbia=time_series_cases$District_of_Columbia$cases[seq(1,1300,by=100)])


fig1 <- ggplot(data_to_plot, aes(x=Date_Alaska,y=Cases_Alaska)) +
 geom_point() + labs(x="Date",y="Cases", title="Alaska") + theme_bw()

 fig2<- ggplot(data_to_plot, aes(x=Date_California,y=Cases_California)) +
 geom_point() + labs(x="Date",y="Cases", title="California") + theme_bw()
 
 fig3<- ggplot(data_to_plot, aes(x=Date_New_Jersey,y=Cases_New_Jersey)) +
 geom_point() + labs(x="Date",y="Cases", title="New Jersey") + theme_bw()
 
 fig4<- ggplot(data_to_plot, aes(x=Date_Tennessee,y=Cases_Tennessee)) +
 geom_point() + labs(x="Date",y="Cases", title="Tennessee") + theme_bw()
 
 fig5<- ggplot(data_to_plot, aes(x=Date_District_of_Columbia,y=Cases_District_of_Columbia)) +
 geom_point() + labs(x="Date",y="Cases", title="District of Columbia") + theme_bw()
 
plot_grid(fig1 + theme(legend.justification = c(0,1)),
          fig2 + theme(legend.justification = c(1,0)),
          fig3 + theme(legend.justification = c(0,1)),
          fig4 + theme(legend.justification = c(1,0)),
          fig5 + theme(legend.justification = c(0,1)),
          align = "v", axis = "lr", nrow=3,
          ncol = 2,labels = LETTERS[1:5],
          rel_heights = c(1,2))
```

edited graphs :)

```{r}
#| echo: false
library(tidyverse)
library(ggplot2)
library(httr)
library(jsonlite)
library(cowplot)

fig1<- ggplot(data_to_plot, aes(x=Date_Alaska,y=Cases_Alaska)) +
 geom_point() + labs(x="Date",y="Cases", title="Alaska") + theme_minimal()

fig2<- ggplot(data_to_plot, aes(x=Date_California,y=Cases_California)) +
 geom_point() + labs(x="Date",y="Cases", title="California") + theme_bw()
 
 fig3<- ggplot(data_to_plot, aes(x=Date_New_Jersey,y=Cases_New_Jersey)) +
 geom_point() + labs(x="Date",y="Cases", title="New Jersey") + theme_bw()
 
 fig4<- ggplot(data_to_plot, aes(x=Date_Tennessee,y=Cases_Tennessee)) +
 geom_point() + labs(x="Date",y="Cases", title="Tennessee") + theme_bw()
 
 fig5<- ggplot(data_to_plot, aes(x=Date_District_of_Columbia,y=Cases_District_of_Columbia)) +
 geom_point() + labs(x="Date",y="Cases", title="District of Columbia") + theme_bw()
 
plot_grid(fig1 + theme(legend.justification = c(0,1)), axis.text.x=element_text(size=3),
          fig2 + theme(legend.justification = c(1,0)), axis.text.x=element_text(size=3),
          fig3 + theme(legend.justification = c(0,1)), axis.text.x=element_text(size=3),
          fig4 + theme(legend.justification = c(1,0)), axis.text.x=element_text(size=3),
          fig5 + theme(legend.justification = c(0,1)), axis.text.x=element_text(size=3),
align = "v", axis = "lr", nrow=3,
          ncol = 2,labels = LETTERS[1:5],
          rel_heights = c(1,2) )

```
