---
title: "Week 7"
author: "Chloe Tan"
date: '2023-10-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 

```{r}
library(tidyverse)
#install.packages(palmerpenguins)
library(palmerpenguins)
glimpse(penguins)

ggplot(data=penguins,mapping=aes(x=bill_depth_mm,y=bill_length_mm,colour=species))+geom_point()+labs(title='Bill depth and length',subtitle='Dimensions for Adelie,Chinstrap,and Gentoo Penguins',x='Bill depth(mm)',y='Bill length(mm)',colour='species',caption = 'source:Palmer Station LTER',scale_color_viridis_d())


```



```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = island)) +
 geom_point() + scale_colour_viridis_d()

```
```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species)) +
 geom_point() + scale_colour_viridis_d()

```
```{R}

ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species, shape = species,
 size = body_mass_g)) +
 geom_point() + scale_colour_viridis_d()
```

```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
 geom_point() + scale_colour_viridis_d()


```

```{R}

ggplot(penguins) +
 aes(x = bill_depth_mm, 
 y = bill_length_mm) + 
 geom_point() +
 facet_grid(species ~ island)
```

```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(species ~ sex)

```

```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(sex ~ species)

```

```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species)

```

```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species, ncol = 2)
```

```{R}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(. ~ species)


```

```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()
```

```{r}
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
 guides(color = "none")

```

```{R}
#install.packages("openintro")
library(openintro)
glimpse(loans_full_schema)


```

```{r}
loans <- loans_full_schema %>%
 select(loan_amount, interest_rate, term, grade, 
 state, annual_income, homeownership, debt_to_income)
glimpse(loans)

```

```{r}
ggplot(loans)+aes(x=loan_amount)+geom_histogram(binwidth=1000)

#binwidth=5000

ggplot(loans)+aes(x=loan_amount)+geom_histogram(binwidth=5000)

#binwidth=20000
ggplot(loans)+aes(x=loan_amount)+geom_histogram(bindwidth=20000)

```

```{r}
ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )

#fill with caterogorical data

ggplot(loans)+aes(x=loan_amount,fill=homeownership)+geom_histogram(binwith=5000,alpha=0.5)+labs(x='Loan amount($)',y='Frequency',title='amounts of Lending Club Loans')

#facet with catergorical data

ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
 facet_wrap(~ homeownership, nrow = 3)
```

```{r}

ggplot(loans, aes(x = loan_amount)) +
 geom_density()
# adjust bandwidth
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 0.5)

#default bandwidth
ggplot(loans, aes(x=loan_amount))+geom_density(adjust=1)

ggplot(loans)+aes(x=loan_amount)+geom_density(adjust=2)

```

```{r}
#customise density plots

ggplot(loans)+aes(x=loan_amount)+geom_density(adjust=2)+labs(x='loan amount($)',y='density',title='amounts of lending club')

#add caterogircal data
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_density(adjust = 2, alpha = 0.5) +
 labs(x = 'Loan amount ($)',y = 'Density',title = 'Amounts of Lending Club loans', fill = 'homeownership')

```

```{r}
ggplot(loans, aes(x = interest_rate)) +
 geom_boxplot()

#outliers
ggplot(loans, aes(x = annual_income)) +
 geom_boxplot()

```

```{r}
#customise
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +theme(axis.ticks.y=element_blank(),axis.text.y=element_blank())

ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +
 theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )


ggplot(loans, aes(x = interest_rate,
 y = grade)) +
 geom_boxplot() +
 labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle='by grade of loan')
```

```{r}
#scatterplot

ggplot(loans, aes(x = 'debt_to_income', y = 'interest_rate')) +
 geom_point()
```

```{r} {ECHO=TRUE,EVAL=TRUE}
#hexplots

ggplot(loans)+aes(x='debt_to_income',y='interest_rate')+geom_hex()

ggplot(loans %>% filter(debt_to_income < 100), 
 aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()

```

```{r}
#barplot

ggplot(loans, aes(x = homeownership)) +
 geom_bar()

```

```{r}

ggplot(loans, aes(x = homeownership, 
 fill = grade)) +
 geom_bar()

# put in the positions 

ggplot(loans)+aes(x=homeownership,fill=grade)+geom_bar(position='fill')

#customise 
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = 'fill') +
labs(x = 'Proportion', y = 'Homeownership', fill = 'Grade', title = 'Grades of Lending Club loans')

```

```{r}

#violin plots

ggplot(loans, aes(x = homeownership, y = loan_amount)) +
 geom_violin()

```

```{r}
#install.packages("ggridges")
library(ggridges)
ggplot(loans,aes(x=loan_amount,y=grade,fill=grade,colour=grade))+geom_density_ridges(alpha=0.5)

```